name: Testing send email custom action

on: 
  workflow_dispatch

jobs:
  sendEmail:
    name: sendemail
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm ci
      - name: Send Email
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          from: ${{ secrets.FROM }}
          to: ${{ secrets.TO }}
          cc: ${{ secrets.CC }}
          subject: ${{ secrets.SUBJECT }}
          html_body: ${{ secrets.HTML_BODY }}
          attachment: "data/attachment.txt"
